include: package:surf_lint_rules/analysis_options.yaml

linter:
  rules:
    avoid_positional_boolean_parameters: false
    always_use_package_imports: false
    avoid_catches_without_on_clauses: false

analyzer:
  errors:
    invalid_annotation_target: ignore
    one_member_abstracts: ignore
  exclude:
    - lib/**/*.g.dart
    - lib/**/*.freezed.dart
